### ISSUE TITLE
Step by Step trials for adapting liboqs-java

### ISSUE THREAD

**Issue by Hatzen** [Hatzen/LibOQSTestApp#7]
Running the circle ci script with ninja manually works as well.  
```
mkdir build && cd build && cmake .. -G"Ninja" -DBUILD_SHARED_LIBS=ON -DOQS_BUILD_ONLY_LIB=ON && ninja install
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib" && mvn package
```
  
Running the circle ci script with custom libpath does not work as the lib is not found. But the temp directory with the given lib exists and ist executable:  
```
export LD_LIBRARY_PATH=
mvn package -P linux -Dliboqs.include.dir="/home/hatzen/linux-test/liboqs/build/include" -Dliboqs.lib.dir="/home/hatzen/linux-test/liboqs/build/lib"
```

replacing liboqs.so `/usr/local/lib` files created by ninja with custom builds fails with 
<details>
<summary>java.lang.UnsatisfiedLinkError: /tmp/oqs-native-lib10622080321236603390/liboqs-jni.so: /usr/lib/x86_64-linux-gnu/libm.so: invalid ELF header </summary>
root@LAPTOP-7N56ITPU:/home/hatzen/linux-test/liboqs-java# export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib" && mvn package
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< org.openquantumsafe:liboqs-java >-------------------
[INFO] Building liboqs-java: Java wrapper for liboqs 1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-antrun-plugin:3.0.0:run (default) @ liboqs-java ---
[INFO] Executing tasks
[INFO] Executed tasks
[INFO]
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ liboqs-java ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ liboqs-java ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- native-maven-plugin:1.0-alpha-9:initialize (generate-shared-oqs-library) @ liboqs-java ---
[INFO]
[INFO] --- native-maven-plugin:1.0-alpha-9:compile (generate-shared-oqs-library) @ liboqs-java ---
[INFO]
[INFO] --- native-maven-plugin:1.0-alpha-9:link (generate-shared-oqs-library) @ liboqs-java ---
[INFO] /bin/sh -c cd '/home/hatzen/linux-test/liboqs-java' && 'gcc' '-shared' '-L/usr/local/lib' '-o/home/hatzen/linux-test/liboqs-java/target/liboqs-java.jar' 'target/objs/handle.o' 'target/objs/KEMs.o' 'target/objs/KeyEncapsulation.o' 'target/objs/Rand.o' 'target/objs/Signature.o' 'target/objs/Sigs.o' '-o' '/home/hatzen/linux-test/liboqs-java/src/main/resources/liboqs-jni.so' '-loqs'
[INFO]
[INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-resources) @ liboqs-java ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ liboqs-java ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ liboqs-java ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.22.0:test (default-test) @ liboqs-java ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.openquantumsafe.KEMTest
Initialize list of enabled KEMs
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.043 s <<< FAILURE! - in org.openquantumsafe.KEMTest
[ERROR] org.openquantumsafe.KEMTest  Time elapsed: 0.041 s  <<< ERROR!
java.lang.UnsatisfiedLinkError: /tmp/oqs-native-lib10622080321236603390/liboqs-jni.so: /usr/lib/x86_64-linux-gnu/libm.so: invalid ELF header
        at org.openquantumsafe.KEMTest.init(KEMTest.java:23)

[INFO] Running org.openquantumsafe.SigTest
Initialize list of enabled Signatures
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 s <<< FAILURE! - in org.openquantumsafe.SigTest
[ERROR] org.openquantumsafe.SigTest  Time elapsed: 0.001 s  <<< ERROR!
java.lang.UnsatisfiedLinkError: /tmp/oqs-native-lib6199952444821869037/liboqs-jni.so: /usr/lib/x86_64-linux-gnu/libm.so: invalid ELF header
        at org.openquantumsafe.SigTest.init(SigTest.java:24)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   KEMTest.init:23 » UnsatisfiedLink /tmp/oqs-native-lib10622080321236603390/libo...
[ERROR]   SigTest.init:24 » UnsatisfiedLink /tmp/oqs-native-lib6199952444821869037/liboq...
[INFO]
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.625 s
[INFO] Finished at: 2021-02-09T21:10:17+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project liboqs-java: There are test failures.
[ERROR]
[ERROR] Please refer to /home/hatzen/linux-test/liboqs-java/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
root@LAPTOP-7N56ITPU:/home/hatzen/linux-test/liboqs-java#
</details>

**Comment by Hatzen** [comment]
Got the same error with making a android.mk file for directly compiling jni sources via ndk for the different abis.

**Comment by Hatzen** [comment]
I did not investigate further on this issue as it does not relate to android. But it seems like an linker issue?
